name: flutter_dibr_do_kospi
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  permission_handler: ^5.0.0+hotfix.9
  carousel_slider: ^2.2.1
  intl: ^0.15.8
  firebase_admob: ^0.9.3
  mockito: ^4.1.1
  google_fonts: ^1.1.0




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - images/pic_a.png
    - images/pic_b.png
    - images/pic_c.png
    - images/pic_d.png
    - images/pic_e.png
    - images/pic_f.png
    - images/pic_g.png
    - images/pic_h.png
    - images/pic_i.png
    - images/pic_j.png
    - images/pic_k.png
    - images/usa.png
    - images/euro.png
    - images/oil.png
    - images/exc.png
    - images/backg1.png
    - images/backgr2.jpg
    - images/main_bg.jpg
    - images/main_bg2.jpg
    - images/main_bg_3.jpg
    - images/main_bg_4.jpg
    - images/etf_bg.jpg
    - images/etf_bg_1.jpg
    - images/etf_bg_2.jpg
    - images/bg1.png
    - images/bg2.png
    - images/bg3.png
    - images/bg4.png
    - images/bg5.png
    - images/bg6.png
    - images/bg7.png
    - images/bg8.png
    - images/bg9.png
    - images/bg10.png
    - images/bg11.png
    - images/ttl1.png
    - images/ttl2.png
    - images/ttl3.png
    - images/ttl4.png
    - images/oil_logo.png
    - images/brent_logo.png
    - images/dubai_logo.png
    - images/wti_logo.png
    - images/wtinew_logo.png
    - images/euro_logo.png
    - images/snp_logo.png
    - images/exc_logo.png
    - images/excnew_logo.png
    - images/exc2_logo.png
    - images/leverage_logo.png
    - images/inverse_logo.png
    - images/leverage_logo_2.png
    - images/inverse_logo_2.png
    - google_fonts/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
